### ISSUE TITLE
Can't install in Arch Linux's `code`

### ISSUE THREAD

**Issue by qarkai** [claui/vscode-aur-packaging#15]
`code` is `The Open Source build of Visual Studio Code (vscode) editor` https://archlinux.org/packages/community/x86_64/code/

Can't find this extension from inside of Code, can't install it using `ext install claui.packaging` command.

**Comment by claui** [comment]
Thanks for bringing this to my attention @qarkai.

By default, the open-source build you mentioned uses the Open VSX Registry, not Microsoft’s proprietary marketplace.
I’m going to publish the extension in the former, too. That should solve the issue.

**Comment by qarkai** [comment]
Ah, right! I totally forgot about this difference. Thanks a lot for extension!

**Comment by claui** [comment]
You’re welcome @qarkai, glad you find it useful!

**Comment by qarkai** [comment]
Despite of HTTP status 500 issue I managed to successfully install extension. I close this issue then.
